[[manager.prepend_keymap]]
on   = "l"
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "q"
run  = "quit --no-cwd-file"
desc = "Quit without changing directory"

[[manager.prepend_keymap]]
on   = "Q"
run  = "quit"
desc = "Quit and change directory"
